package pl.coderslab;

public enum Enums {
    NOWHERE, LOGIN, MAIN_APP, PROJECTS, PROJECT_PREVIEW, PROJECT_COMMENTS, PLACE_ADMIN,

    ALL, UNDONE, URGENT,

    PROJECT_CHANGE_NAME, PROJECT_CHANGE_DESCRIPTION, PROJECT_CHANGE_URGENT, PROJECT_CHANGE_DONE, PROJECT_CHANGE_PROGRESS_ANALYSIS, PROJECT_CHANGE_PROGRESS_STRUCTURE, PROJECT_CHANGE_PROGRESS_DESIGN, PROJECT_CHANGE_PROGRESS_FRONTEND, PROJECT_CHANGE_PROGRESS_BACKEND, PROJECT_CHANGE_PROGRESS_TESTING, PROJECT_CHANGE_PROGRESS_OPTIMIZATION, PROJECT_CHANGE_DEADLINE
}

